//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ad()
        {
            this.AdFavorites = new HashSet<AdFavorite>();
            this.AdsViewers = new HashSet<AdsViewer>();
            this.Chattings = new HashSet<Chatting>();
            this.Reports = new HashSet<Report>();
            this.UsersPurchasesAds = new HashSet<UsersPurchasesAd>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
        public decimal Price { get; set; }
        public bool IsTop { get; set; }
        public bool IsApprove { get; set; }
        public Nullable<int> FkSubCategory_Id { get; set; }
        public int FkCategory_Id { get; set; }
        public int FkAlbum_Id { get; set; }
        public int FkLog_Id { get; set; }
        public int FkUser_Id { get; set; }
        public int FkLocation_Id { get; set; }
        public string PhoneNumber { get; set; }
        public bool IsAllowMessaging { get; set; }
        public bool IsPostWithOutPhoneNumber { get; set; }
        public bool IsAutoPost { get; set; }
        public int CountAutoPostToNow { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdFavorite> AdFavorites { get; set; }
        public virtual Album Album { get; set; }
        public virtual Category Category { get; set; }
        public virtual Location Location { get; set; }
        public virtual Log Log { get; set; }
        public virtual SubCategory SubCategory { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdsViewer> AdsViewers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chatting> Chattings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Report> Reports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersPurchasesAd> UsersPurchasesAds { get; set; }
    }
}
