//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SilgaramEntities : DbContext
    {
        public SilgaramEntities()
            : base("name=SilgaramEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<AdFavorite> AdFavorites { get; set; }
        public virtual DbSet<Ad> Ads { get; set; }
        public virtual DbSet<AdsSlider> AdsSliders { get; set; }
        public virtual DbSet<AdsViewer> AdsViewers { get; set; }
        public virtual DbSet<AlbumFile> AlbumFiles { get; set; }
        public virtual DbSet<Album> Albums { get; set; }
        public virtual DbSet<AppsInformation> AppsInformations { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<ChatMessage> ChatMessages { get; set; }
        public virtual DbSet<Chatting> Chattings { get; set; }
        public virtual DbSet<CommercialBanner> CommercialBanners { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<File> Files { get; set; }
        public virtual DbSet<FileType> FileTypes { get; set; }
        public virtual DbSet<Following> Followings { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<History> Histories { get; set; }
        public virtual DbSet<HistoryDetail> HistoryDetails { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<LanguageType> LanguageTypes { get; set; }
        public virtual DbSet<LanguageUsing> LanguageUsings { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<Nationality> Nationalities { get; set; }
        public virtual DbSet<NotificationsIsRead> NotificationsIsReads { get; set; }
        public virtual DbSet<OfferFavorite> OfferFavorites { get; set; }
        public virtual DbSet<Offer> Offers { get; set; }
        public virtual DbSet<OffersViewer> OffersViewers { get; set; }
        public virtual DbSet<Page> Pages { get; set; }
        public virtual DbSet<PagesAllow> PagesAllows { get; set; }
        public virtual DbSet<PagesRole> PagesRoles { get; set; }
        public virtual DbSet<PagesRoleType> PagesRoleTypes { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<PointPackage> PointPackages { get; set; }
        public virtual DbSet<PositionType> PositionTypes { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<ReportType> ReportTypes { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<SocialStatu> SocialStatus { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<SubCategory> SubCategories { get; set; }
        public virtual DbSet<SubMenu> SubMenus { get; set; }
        public virtual DbSet<TechnicalSupport> TechnicalSupports { get; set; }
        public virtual DbSet<TechnicalSupportRead> TechnicalSupportReads { get; set; }
        public virtual DbSet<UserInformation> UserInformations { get; set; }
        public virtual DbSet<UserLogin> UserLogins { get; set; }
        public virtual DbSet<UserPointPackage> UserPointPackages { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UsersFollowing> UsersFollowings { get; set; }
        public virtual DbSet<UsersPrivateNotify> UsersPrivateNotifies { get; set; }
        public virtual DbSet<UsersPurchasesAd> UsersPurchasesAds { get; set; }
        public virtual DbSet<UsersPurchasesOffer> UsersPurchasesOffers { get; set; }
    }
}
