//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PointPackage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PointPackage()
        {
            this.UserPointPackages = new HashSet<UserPointPackage>();
        }
    
        public int Id { get; set; }
        public string NameAr { get; set; }
        public string NameEn { get; set; }
        public int Points { get; set; }
        public decimal Price { get; set; }
        public int FkLog_Id { get; set; }
    
        public virtual Log Log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserPointPackage> UserPointPackages { get; set; }
    }
}
