//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInformation
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string MediumName { get; set; }
        public string LastName { get; set; }
        public string NationalId { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public int FkImage_Id { get; set; }
        public Nullable<int> FKAddress_Id { get; set; }
        public Nullable<int> FkNationality_Id { get; set; }
        public Nullable<int> FKGender_Id { get; set; }
        public Nullable<int> FKSocialStatus_Id { get; set; }
        public Nullable<int> FKJob_Id { get; set; }
        public Nullable<int> FKLanguage_Id { get; set; }
        public int FkFollowing_Id { get; set; }
        public string PhoneNumber { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual File File { get; set; }
        public virtual Following Following { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Job Job { get; set; }
        public virtual Language Language { get; set; }
        public virtual Nationality Nationality { get; set; }
        public virtual SocialStatu SocialStatu { get; set; }
        public virtual User User { get; set; }
    }
}
