//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public History()
        {
            this.HistoryDetails = new HashSet<HistoryDetail>();
            this.NotificationsIsReads = new HashSet<NotificationsIsRead>();
            this.UsersPrivateNotifies = new HashSet<UsersPrivateNotify>();
        }
    
        public int Id { get; set; }
        public System.DateTime DateTime { get; set; }
        public string RedirectUrl { get; set; }
        public int FkState_Id { get; set; }
        public Nullable<int> FkUser_Id { get; set; }
        public int FKPage_Id { get; set; }
        public Nullable<int> FkLog_Id { get; set; }
        public string TitleEn { get; set; }
        public string TitleAr { get; set; }
    
        public virtual Log Log { get; set; }
        public virtual Page Page { get; set; }
        public virtual State State { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoryDetail> HistoryDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotificationsIsRead> NotificationsIsReads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersPrivateNotify> UsersPrivateNotifies { get; set; }
    }
}
