//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LanguageUsing
    {
        public int Id { get; set; }
        public bool IsDefault { get; set; }
        public int FKLanguageType_Id { get; set; }
        public int FKLanguage_Id { get; set; }
    
        public virtual Language Language { get; set; }
        public virtual LanguageType LanguageType { get; set; }
    }
}
