//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Offer()
        {
            this.OfferFavorites = new HashSet<OfferFavorite>();
            this.UsersPurchasesOffers = new HashSet<UsersPurchasesOffer>();
            this.OffersViewers = new HashSet<OffersViewer>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public System.DateTime EndDateTime { get; set; }
        public decimal Price { get; set; }
        public bool IsTop { get; set; }
        public int FkAlbum_Id { get; set; }
        public int FkLog_Id { get; set; }
        public int DiscountRate { get; set; }
        public string SmallDiscription { get; set; }
        public int FkCategory_Id { get; set; }
        public int FkSubCategory_Id { get; set; }
    
        public virtual Album Album { get; set; }
        public virtual Category Category { get; set; }
        public virtual Log Log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfferFavorite> OfferFavorites { get; set; }
        public virtual SubCategory SubCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersPurchasesOffer> UsersPurchasesOffers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OffersViewer> OffersViewers { get; set; }
    }
}
