//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagesAllow
    {
        public int Id { get; set; }
        public bool IsAllowNotify { get; set; }
        public bool IsAllowLog { get; set; }
        public int FkLog_Id { get; set; }
        public int FkPage_Id { get; set; }
    
        public virtual Log Log { get; set; }
        public virtual Page Page { get; set; }
    }
}
