//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Token {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Token() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DAL.Resource.Token", typeof(Token).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Settings.
        /// </summary>
        public static string AccountSettings {
            get {
                return ResourceManager.GetString("AccountSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acctive Account.
        /// </summary>
        public static string AcctiveAccount {
            get {
                return ResourceManager.GetString("AcctiveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad Fovorite.
        /// </summary>
        public static string AdFovorite {
            get {
                return ResourceManager.GetString("AdFovorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad Id.
        /// </summary>
        public static string AdId {
            get {
                return ResourceManager.GetString("AdId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Login.
        /// </summary>
        public static string AdminLogin {
            get {
                return ResourceManager.GetString("AdminLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad Not Found.
        /// </summary>
        public static string AdNotFound {
            get {
                return ResourceManager.GetString("AdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad UnFovorite.
        /// </summary>
        public static string AdUnFovorite {
            get {
                return ResourceManager.GetString("AdUnFovorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ago.
        /// </summary>
        public static string Ago {
            get {
                return ResourceManager.GetString("Ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All User Count.
        /// </summary>
        public static string AllUserCount {
            get {
                return ResourceManager.GetString("AllUserCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;.
        /// </summary>
        public static string AndChar {
            get {
                return ResourceManager.GetString("AndChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And He Added The Following.
        /// </summary>
        public static string AndHeAddedTheFollowing {
            get {
                return ResourceManager.GetString("AndHeAddedTheFollowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And He Updated The Following.
        /// </summary>
        public static string AndHeUpdatedTheFollowing {
            get {
                return ResourceManager.GetString("AndHeUpdatedTheFollowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And Name Her.
        /// </summary>
        public static string AndNameHer {
            get {
                return ResourceManager.GetString("AndNameHer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And Paste The Code In Appication.
        /// </summary>
        public static string AndPasteTheCodeInAppication {
            get {
                return ResourceManager.GetString("AndPasteTheCodeInAppication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sela Gram.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic.
        /// </summary>
        public static string Arabic {
            get {
                return ResourceManager.GetString("Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are You Sure Delete.
        /// </summary>
        public static string AreYouSureDelete {
            get {
                return ResourceManager.GetString("AreYouSureDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auction.
        /// </summary>
        public static string Auction {
            get {
                return ResourceManager.GetString("Auction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Auction.
        /// </summary>
        public static string AuctionAr {
            get {
                return ResourceManager.GetString("AuctionAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Auction.
        /// </summary>
        public static string AuctionEn {
            get {
                return ResourceManager.GetString("AuctionEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auction Is Finshed.
        /// </summary>
        public static string AuctionIsFinshed {
            get {
                return ResourceManager.GetString("AuctionIsFinshed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auction Not Found.
        /// </summary>
        public static string AuctionNotFound {
            get {
                return ResourceManager.GetString("AuctionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auctions.
        /// </summary>
        public static string Auctions {
            get {
                return ResourceManager.GetString("Auctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auctions Not Found.
        /// </summary>
        public static string AuctionsNotFound {
            get {
                return ResourceManager.GetString("AuctionsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar.
        /// </summary>
        public static string Avatar {
            get {
                return ResourceManager.GetString("Avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Data.
        /// </summary>
        public static string BasicData {
            get {
                return ResourceManager.GetString("BasicData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before Used.
        /// </summary>
        public static string BeforeUsed {
            get {
                return ResourceManager.GetString("BeforeUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bidders In Auction.
        /// </summary>
        public static string BiddersInAuction {
            get {
                return ResourceManager.GetString("BiddersInAuction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ ووقت الشراء.
        /// </summary>
        public static string BuyDateTime {
            get {
                return ResourceManager.GetString("BuyDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buying Succeeded.
        /// </summary>
        public static string BuyingSucceeded {
            get {
                return ResourceManager.GetString("BuyingSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caht Id.
        /// </summary>
        public static string CahtId {
            get {
                return ResourceManager.GetString("CahtId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can Not Delete.
        /// </summary>
        public static string CanNotDelete {
            get {
                return ResourceManager.GetString("CanNotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can Not Display.
        /// </summary>
        public static string CanNotDisplay {
            get {
                return ResourceManager.GetString("CanNotDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can Not Display Messags For You.
        /// </summary>
        public static string CanNotDisplayMessagsForYou {
            get {
                return ResourceManager.GetString("CanNotDisplayMessagsForYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can Not Dublicated Language.
        /// </summary>
        public static string CanNotDublicatedLanguage {
            get {
                return ResourceManager.GetString("CanNotDublicatedLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can Not Dublicated Role.
        /// </summary>
        public static string CanNotDublicatedRole {
            get {
                return ResourceManager.GetString("CanNotDublicatedRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can Not Duplicate.
        /// </summary>
        public static string CanNotDuplicate {
            get {
                return ResourceManager.GetString("CanNotDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can Not Following.
        /// </summary>
        public static string CanNotFollowing {
            get {
                return ResourceManager.GetString("CanNotFollowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can Not Paid.
        /// </summary>
        public static string CanNotPaid {
            get {
                return ResourceManager.GetString("CanNotPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can Not Save File.
        /// </summary>
        public static string CanNotSaveFile {
            get {
                return ResourceManager.GetString("CanNotSaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can Not Update Your Information From Here.
        /// </summary>
        public static string CanNotUpdateYourInformationFromHere {
            get {
                return ResourceManager.GetString("CanNotUpdateYourInformationFromHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can Noy Buy Live Ad.
        /// </summary>
        public static string CanNoyBuyLiveAd {
            get {
                return ResourceManager.GetString("CanNoyBuyLiveAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captured.
        /// </summary>
        public static string Captured {
            get {
                return ResourceManager.GetString("Captured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Avatar.
        /// </summary>
        public static string ChangeAvatar {
            get {
                return ResourceManager.GetString("ChangeAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Not Found.
        /// </summary>
        public static string ChatNotFound {
            get {
                return ResourceManager.GetString("ChatNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked.
        /// </summary>
        public static string Checked {
            get {
                return ResourceManager.GetString("Checked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chooes Icons.
        /// </summary>
        public static string ChooesIcons {
            get {
                return ResourceManager.GetString("ChooesIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chooes Language.
        /// </summary>
        public static string ChooesLanguage {
            get {
                return ResourceManager.GetString("ChooesLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chooes Product.
        /// </summary>
        public static string ChooesProduct {
            get {
                return ResourceManager.GetString("ChooesProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities.
        /// </summary>
        public static string Cities {
            get {
                return ResourceManager.GetString("Cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string CityAr {
            get {
                return ResourceManager.GetString("CityAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string CityEn {
            get {
                return ResourceManager.GetString("CityEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse.
        /// </summary>
        public static string Collapse {
            get {
                return ResourceManager.GetString("Collapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries.
        /// </summary>
        public static string Countries {
            get {
                return ResourceManager.GetString("Countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string CountryAr {
            get {
                return ResourceManager.GetString("CountryAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string CountryEn {
            get {
                return ResourceManager.GetString("CountryEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Not Found.
        /// </summary>
        public static string CountryNotFound {
            get {
                return ResourceManager.GetString("CountryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count User.
        /// </summary>
        public static string CountUser {
            get {
                return ResourceManager.GetString("CountUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create And Update.
        /// </summary>
        public static string CreateAndUpdate {
            get {
                return ResourceManager.GetString("CreateAndUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create By.
        /// </summary>
        public static string CreateBy {
            get {
                return ResourceManager.GetString("CreateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Date Time.
        /// </summary>
        public static string CreateDateTime {
            get {
                return ResourceManager.GetString("CreateDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        public static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New User.
        /// </summary>
        public static string CreateNewUser {
            get {
                return ResourceManager.GetString("CreateNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Price.
        /// </summary>
        public static string CurrentPrice {
            get {
                return ResourceManager.GetString("CurrentPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Not Found.
        /// </summary>
        public static string DataNotFound {
            get {
                return ResourceManager.GetString("DataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear.
        /// </summary>
        public static string Dear {
            get {
                return ResourceManager.GetString("Dear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Confirm.
        /// </summary>
        public static string DeleteConfirm {
            get {
                return ResourceManager.GetString("DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabice Description .
        /// </summary>
        public static string DescriptionAr {
            get {
                return ResourceManager.GetString("DescriptionAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Description .
        /// </summary>
        public static string DescriptionEn {
            get {
                return ResourceManager.GetString("DescriptionEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        public static string Display {
            get {
                return ResourceManager.GetString("Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date Time.
        /// </summary>
        public static string EndDateTime {
            get {
                return ResourceManager.GetString("EndDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date Time Must Be More Than Current.
        /// </summary>
        public static string EndDateTimeMustBeMoreThanCurrent {
            get {
                return ResourceManager.GetString("EndDateTimeMustBeMoreThanCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndDateTimeMustBeMoreTthanStartDateTime.
        /// </summary>
        public static string EndDateTimeMustBeMoreThanStartDateTime {
            get {
                return ResourceManager.GetString("EndDateTimeMustBeMoreThanStartDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Email Name And Password.
        /// </summary>
        public static string EnterEmailNameAndPassword {
            get {
                return ResourceManager.GetString("EnterEmailNameAndPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter UserName And Password.
        /// </summary>
        public static string EnterUserNameAndPassword {
            get {
                return ResourceManager.GetString("EnterUserNameAndPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter User Serial Number.
        /// </summary>
        public static string EnterUserSerialNo {
            get {
                return ResourceManager.GetString("EnterUserSerialNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Confirm Password.
        /// </summary>
        public static string ErrorConfirmPassword {
            get {
                return ResourceManager.GetString("ErrorConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Duplicate.
        /// </summary>
        public static string ErrorDuplicate {
            get {
                return ResourceManager.GetString("ErrorDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Payment.
        /// </summary>
        public static string ErrorPayment {
            get {
                return ResourceManager.GetString("ErrorPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        public static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired.
        /// </summary>
        public static string EXPIRED {
            get {
                return ResourceManager.GetString("EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filed Bidder.
        /// </summary>
        public static string FiledBidder {
            get {
                return ResourceManager.GetString("FiledBidder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filed Is Required.
        /// </summary>
        public static string FiledIsRequired {
            get {
                return ResourceManager.GetString("FiledIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow.
        /// </summary>
        public static string Follow {
            get {
                return ResourceManager.GetString("Follow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For.
        /// </summary>
        public static string For {
            get {
                return ResourceManager.GetString("For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get User Logins.
        /// </summary>
        public static string GetUserLogins {
            get {
                return ResourceManager.GetString("GetUserLogins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Been Deleted.
        /// </summary>
        public static string HasBeenDeleted {
            get {
                return ResourceManager.GetString("HasBeenDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Been Updated.
        /// </summary>
        public static string HasBeenUpdated {
            get {
                return ResourceManager.GetString("HasBeenUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Buy The.
        /// </summary>
        public static string HasBuyThe {
            get {
                return ResourceManager.GetString("HasBuyThe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Created The.
        /// </summary>
        public static string HasCreatedThe {
            get {
                return ResourceManager.GetString("HasCreatedThe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Deleted The.
        /// </summary>
        public static string HasDeletedThe {
            get {
                return ResourceManager.GetString("HasDeletedThe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Send The Message.
        /// </summary>
        public static string HasSendTheMessage {
            get {
                return ResourceManager.GetString("HasSendTheMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Updated The.
        /// </summary>
        public static string HasUpdatedThe {
            get {
                return ResourceManager.GetString("HasUpdatedThe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Win The.
        /// </summary>
        public static string HasWinThe {
            get {
                return ResourceManager.GetString("HasWinThe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I Can&apos;t Load Products Becuse This Auction Is Started.
        /// </summary>
        public static string ICanNotLoadProductsBecuseThisAuctionIsStarted {
            get {
                return ResourceManager.GetString("ICanNotLoadProductsBecuseThisAuctionIsStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I Cant Call To Server.
        /// </summary>
        public static string ICantCallToServer {
            get {
                return ResourceManager.GetString("ICantCallToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        public static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Profile.
        /// </summary>
        public static string ImageProfile {
            get {
                return ResourceManager.GetString("ImageProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In.
        /// </summary>
        public static string In {
            get {
                return ResourceManager.GetString("In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In ADay.
        /// </summary>
        public static string InADay {
            get {
                return ResourceManager.GetString("InADay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Time.
        /// </summary>
        public static string InTime {
            get {
                return ResourceManager.GetString("InTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Data.
        /// </summary>
        public static string InvalidData {
            get {
                return ResourceManager.GetString("InvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Date.
        /// </summary>
        public static string InvalidDate {
            get {
                return ResourceManager.GetString("InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Number.
        /// </summary>
        public static string InvalidNumber {
            get {
                return ResourceManager.GetString("InvalidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Allow Log.
        /// </summary>
        public static string IsAllowLog {
            get {
                return ResourceManager.GetString("IsAllowLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Allow Notify.
        /// </summary>
        public static string IsAllowNotify {
            get {
                return ResourceManager.GetString("IsAllowNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Block.
        /// </summary>
        public static string IsBlock {
            get {
                return ResourceManager.GetString("IsBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Finshed.
        /// </summary>
        public static string IsFinshed {
            get {
                return ResourceManager.GetString("IsFinshed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Return Points.
        /// </summary>
        public static string IsReturnPoints {
            get {
                return ResourceManager.GetString("IsReturnPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Started.
        /// </summary>
        public static string IsStarted {
            get {
                return ResourceManager.GetString("IsStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Success.
        /// </summary>
        public static string IsSuccess {
            get {
                return ResourceManager.GetString("IsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s Been Rejected.
        /// </summary>
        public static string ItsBeenRejected {
            get {
                return ResourceManager.GetString("ItsBeenRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;ve Been Approved.
        /// </summary>
        public static string IveBeenApproved {
            get {
                return ResourceManager.GetString("IveBeenApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job.
        /// </summary>
        public static string Job {
            get {
                return ResourceManager.GetString("Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jobs.
        /// </summary>
        public static string Jobs {
            get {
                return ResourceManager.GetString("Jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just Now.
        /// </summary>
        public static string JustNow {
            get {
                return ResourceManager.GetString("JustNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        public static string Logs {
            get {
                return ResourceManager.GetString("Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        public static string Management {
            get {
                return ResourceManager.GetString("Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        public static string Manager {
            get {
                return ResourceManager.GetString("Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Married.
        /// </summary>
        public static string Married {
            get {
                return ResourceManager.GetString("Married", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Length.
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Length Number.
        /// </summary>
        public static string MaxLengthNumber {
            get {
                return ResourceManager.GetString("MaxLengthNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium Name.
        /// </summary>
        public static string MediumName {
            get {
                return ResourceManager.GetString("MediumName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menus.
        /// </summary>
        public static string Menus {
            get {
                return ResourceManager.GetString("Menus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Length.
        /// </summary>
        public static string MinimumLength {
            get {
                return ResourceManager.GetString("MinimumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Points.
        /// </summary>
        public static string MinimumPoints {
            get {
                return ResourceManager.GetString("MinimumPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        public static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Months.
        /// </summary>
        public static string Months {
            get {
                return ResourceManager.GetString("Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Name.
        /// </summary>
        public static string NameAr {
            get {
                return ResourceManager.GetString("NameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Name.
        /// </summary>
        public static string NameEn {
            get {
                return ResourceManager.GetString("NameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NationalId.
        /// </summary>
        public static string NationalId {
            get {
                return ResourceManager.GetString("NationalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationalities.
        /// </summary>
        public static string Nationalities {
            get {
                return ResourceManager.GetString("Nationalities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        public static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data For Save.
        /// </summary>
        public static string NoDataForSave {
            get {
                return ResourceManager.GetString("NoDataForSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data More.
        /// </summary>
        public static string NoDataMore {
            get {
                return ResourceManager.GetString("NoDataMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No More Notifications.
        /// </summary>
        public static string NoMoreNotifications {
            get {
                return ResourceManager.GetString("NoMoreNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Notifications Found.
        /// </summary>
        public static string NoNotificationsFound {
            get {
                return ResourceManager.GetString("NoNotificationsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Captured.
        /// </summary>
        public static string NotCaptured {
            get {
                return ResourceManager.GetString("NotCaptured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Created.
        /// </summary>
        public static string NotCreated {
            get {
                return ResourceManager.GetString("NotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify.
        /// </summary>
        public static string Notify {
            get {
                return ResourceManager.GetString("Notify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify Not Found.
        /// </summary>
        public static string NotifyNotFound {
            get {
                return ResourceManager.GetString("NotifyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Save Change.
        /// </summary>
        public static string NotSaveChange {
            get {
                return ResourceManager.GetString("NotSaveChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Not Valid.
        /// </summary>
        public static string NumberNotValid {
            get {
                return ResourceManager.GetString("NumberNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string of {
            get {
                return ResourceManager.GetString("of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer Fovoriteed.
        /// </summary>
        public static string OfferFovoriteed {
            get {
                return ResourceManager.GetString("OfferFovoriteed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer Not Found.
        /// </summary>
        public static string OfferNotFound {
            get {
                return ResourceManager.GetString("OfferNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer Un Fovorite.
        /// </summary>
        public static string OfferUnFovorite {
            get {
                return ResourceManager.GetString("OfferUnFovorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password Invalid.
        /// </summary>
        public static string OldPasswordInvalid {
            get {
                return ResourceManager.GetString("OldPasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Day.
        /// </summary>
        public static string OneDay {
            get {
                return ResourceManager.GetString("OneDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Hour.
        /// </summary>
        public static string OneHour {
            get {
                return ResourceManager.GetString("OneHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Minute.
        /// </summary>
        public static string OneMinute {
            get {
                return ResourceManager.GetString("OneMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Month.
        /// </summary>
        public static string OneMonth {
            get {
                return ResourceManager.GetString("OneMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Year.
        /// </summary>
        public static string OneYear {
            get {
                return ResourceManager.GetString("OneYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordere Number.
        /// </summary>
        public static string OrdereNumber {
            get {
                return ResourceManager.GetString("OrdereNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string Overview {
            get {
                return ResourceManager.GetString("Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        public static string Pages {
            get {
                return ResourceManager.GetString("Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages Allow.
        /// </summary>
        public static string PagesAllow {
            get {
                return ResourceManager.GetString("PagesAllow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages Roles.
        /// </summary>
        public static string PagesRoles {
            get {
                return ResourceManager.GetString("PagesRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages Role Types.
        /// </summary>
        public static string PagesRoleTypes {
            get {
                return ResourceManager.GetString("PagesRoleTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid.
        /// </summary>
        public static string Paid {
            get {
                return ResourceManager.GetString("Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords Are Not Consistent.
        /// </summary>
        public static string PasswordsAreNotConsistent {
            get {
                return ResourceManager.GetString("PasswordsAreNotConsistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paymen Not Found.
        /// </summary>
        public static string PaymenNotFound {
            get {
                return ResourceManager.GetString("PaymenNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Info.
        /// </summary>
        public static string PersonalInfo {
            get {
                return ResourceManager.GetString("PersonalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phones.
        /// </summary>
        public static string Phones {
            get {
                return ResourceManager.GetString("Phones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Copy This Code.
        /// </summary>
        public static string PleaseCopyThisCode {
            get {
                return ResourceManager.GetString("PleaseCopyThisCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point Package.
        /// </summary>
        public static string PointPackage {
            get {
                return ResourceManager.GetString("PointPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Point Package .
        /// </summary>
        public static string PointPackageAr {
            get {
                return ResourceManager.GetString("PointPackageAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Point Package.
        /// </summary>
        public static string PointPackageEn {
            get {
                return ResourceManager.GetString("PointPackageEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point Package Found.
        /// </summary>
        public static string PointPackageFound {
            get {
                return ResourceManager.GetString("PointPackageFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point Packages.
        /// </summary>
        public static string PointPackages {
            get {
                return ResourceManager.GetString("PointPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        public static string Points {
            get {
                return ResourceManager.GetString("Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Dobul Click For Remove Any Image.
        /// </summary>
        public static string PressDobulClickForRemoveAnyImage {
            get {
                return ResourceManager.GetString("PressDobulClickForRemoveAnyImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string ProductAr {
            get {
                return ResourceManager.GetString("ProductAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string ProductEn {
            get {
                return ResourceManager.GetString("ProductEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Not Found.
        /// </summary>
        public static string ProductNotFound {
            get {
                return ResourceManager.GetString("ProductNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Selected.
        /// </summary>
        public static string ProductSelected {
            get {
                return ResourceManager.GetString("ProductSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Sold.
        /// </summary>
        public static string ProductSold {
            get {
                return ResourceManager.GetString("ProductSold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products Sold.
        /// </summary>
        public static string ProductsSold {
            get {
                return ResourceManager.GetString("ProductsSold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Account.
        /// </summary>
        public static string ProfileAccount {
            get {
                return ResourceManager.GetString("ProfileAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province.
        /// </summary>
        public static string Province {
            get {
                return ResourceManager.GetString("Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate Must be More Than 5  Less Than 0.
        /// </summary>
        public static string RateMustbeMoreThan5AndLessThan0 {
            get {
                return ResourceManager.GetString("RateMustbeMoreThan5AndLessThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirected.
        /// </summary>
        public static string REDIRECTED {
            get {
                return ResourceManager.GetString("REDIRECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload Data.
        /// </summary>
        public static string ReloadData {
            get {
                return ResourceManager.GetString("ReloadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Type Id.
        /// </summary>
        public static string ReportTypeId {
            get {
                return ResourceManager.GetString("ReportTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Type Not Found.
        /// </summary>
        public static string ReportTypeNotFound {
            get {
                return ResourceManager.GetString("ReportTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Buy Ad.
        /// </summary>
        public static string RequestBuyAd {
            get {
                return ResourceManager.GetString("RequestBuyAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        public static string Review {
            get {
                return ResourceManager.GetString("Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Change.
        /// </summary>
        public static string SaveChange {
            get {
                return ResourceManager.GetString("SaveChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        public static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent.
        /// </summary>
        public static string Sent {
            get {
                return ResourceManager.GetString("Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial.
        /// </summary>
        public static string Serial {
            get {
                return ResourceManager.GetString("Serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number.
        /// </summary>
        public static string SerialNumber {
            get {
                return ResourceManager.GetString("SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing.
        /// </summary>
        public static string Showing {
            get {
                return ResourceManager.GetString("Showing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show More.
        /// </summary>
        public static string ShowMore {
            get {
                return ResourceManager.GetString("ShowMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignIn.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single.
        /// </summary>
        public static string Single {
            get {
                return ResourceManager.GetString("Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Status.
        /// </summary>
        public static string SocialStatus {
            get {
                return ResourceManager.GetString("SocialStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some Error In Server.
        /// </summary>
        public static string SomeErrorInServer {
            get {
                return ResourceManager.GetString("SomeErrorInServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date Time.
        /// </summary>
        public static string StartDateTime {
            get {
                return ResourceManager.GetString("StartDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date Time Must Be More Than Or Equal  current Date Time.
        /// </summary>
        public static string StartDateTimeMustBeMoreTthanOrEqualCurrent {
            get {
                return ResourceManager.GetString("StartDateTimeMustBeMoreTthanOrEqualCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Not Found.
        /// </summary>
        public static string StateNotFound {
            get {
                return ResourceManager.GetString("StateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to س.
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Category.
        /// </summary>
        public static string SubCategory {
            get {
                return ResourceManager.GetString("SubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Menu.
        /// </summary>
        public static string SubMenu {
            get {
                return ResourceManager.GetString("SubMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Menus.
        /// </summary>
        public static string SubMenus {
            get {
                return ResourceManager.GetString("SubMenus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success Bidder.
        /// </summary>
        public static string SuccessBidder {
            get {
                return ResourceManager.GetString("SuccessBidder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success Payment.
        /// </summary>
        public static string SuccessPayment {
            get {
                return ResourceManager.GetString("SuccessPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success Reported.
        /// </summary>
        public static string SuccessReported {
            get {
                return ResourceManager.GetString("SuccessReported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor.
        /// </summary>
        public static string Supervisor {
            get {
                return ResourceManager.GetString("Supervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        public static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        public static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical Support.
        /// </summary>
        public static string TechnicalSupport {
            get {
                return ResourceManager.GetString("TechnicalSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical Support Found.
        /// </summary>
        public static string TechnicalSupportFound {
            get {
                return ResourceManager.GetString("TechnicalSupportFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The User Has.
        /// </summary>
        public static string TheUserHas {
            get {
                return ResourceManager.GetString("TheUserHas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Not For U.
        /// </summary>
        public static string ThisNotForU {
            get {
                return ResourceManager.GetString("ThisNotForU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Page For.
        /// </summary>
        public static string ThisPageFor {
            get {
                return ResourceManager.GetString("ThisPageFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token Not Valid.
        /// </summary>
        public static string TokenNotValid {
            get {
                return ResourceManager.GetString("TokenNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two Days.
        /// </summary>
        public static string TwoDays {
            get {
                return ResourceManager.GetString("TwoDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two Hour.
        /// </summary>
        public static string TwoHour {
            get {
                return ResourceManager.GetString("TwoHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two Minute.
        /// </summary>
        public static string TwoMinute {
            get {
                return ResourceManager.GetString("TwoMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two Months.
        /// </summary>
        public static string TwoMonths {
            get {
                return ResourceManager.GetString("TwoMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two Years.
        /// </summary>
        public static string TwoYears {
            get {
                return ResourceManager.GetString("TwoYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un Checked.
        /// </summary>
        public static string UnChecked {
            get {
                return ResourceManager.GetString("UnChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpaid.
        /// </summary>
        public static string UNPAID {
            get {
                return ResourceManager.GetString("UNPAID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        public static string Updated {
            get {
                return ResourceManager.GetString("Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Images.
        /// </summary>
        public static string UploadImages {
            get {
                return ResourceManager.GetString("UploadImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploads.
        /// </summary>
        public static string Uploads {
            get {
                return ResourceManager.GetString("Uploads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Login.
        /// </summary>
        public static string UserLogin {
            get {
                return ResourceManager.GetString("UserLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Logins.
        /// </summary>
        public static string UserLogins {
            get {
                return ResourceManager.GetString("UserLogins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Not Found.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Point Package.
        /// </summary>
        public static string UserPointPackage {
            get {
                return ResourceManager.GetString("UserPointPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Point Packages.
        /// </summary>
        public static string UserPointPackages {
            get {
                return ResourceManager.GetString("UserPointPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Profile.
        /// </summary>
        public static string UserProfile {
            get {
                return ResourceManager.GetString("UserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users Read.
        /// </summary>
        public static string UsersRead {
            get {
                return ResourceManager.GetString("UsersRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewAll.
        /// </summary>
        public static string ViewAll {
            get {
                return ResourceManager.GetString("ViewAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widow.
        /// </summary>
        public static string Widow {
            get {
                return ResourceManager.GetString("Widow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widower.
        /// </summary>
        public static string Widower {
            get {
                return ResourceManager.GetString("Widower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win.
        /// </summary>
        public static string Win {
            get {
                return ResourceManager.GetString("Win", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With.
        /// </summary>
        public static string With {
            get {
                return ResourceManager.GetString("With", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years.
        /// </summary>
        public static string Years {
            get {
                return ResourceManager.GetString("Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes Delete.
        /// </summary>
        public static string YesDelete {
            get {
                return ResourceManager.GetString("YesDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Blocked.
        /// </summary>
        public static string YouBlocked {
            get {
                return ResourceManager.GetString("YouBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Can Not Create Chat For Youre Ads.
        /// </summary>
        public static string YouCanNotCreateChatForYoureAds {
            get {
                return ResourceManager.GetString("YouCanNotCreateChatForYoureAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Can Not Report For Your&apos;e Ads.
        /// </summary>
        public static string YouCanNotReportForYoureAds {
            get {
                return ResourceManager.GetString("YouCanNotReportForYoureAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have enough points..
        /// </summary>
        public static string YouDonNoHaveEnoughPoints {
            get {
                return ResourceManager.GetString("YouDonNoHaveEnoughPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Not Allowed Show The Technical Support Message.
        /// </summary>
        public static string YouNotAllowedShowTheTechnicalSupportMessage {
            get {
                return ResourceManager.GetString("YouNotAllowedShowTheTechnicalSupportMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Not Allowed Show This Notify.
        /// </summary>
        public static string YouNotAllowedShowThisNotify {
            get {
                return ResourceManager.GetString("YouNotAllowedShowThisNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Not Client.
        /// </summary>
        public static string YouNotClient {
            get {
                return ResourceManager.GetString("YouNotClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Not Created This Ad.
        /// </summary>
        public static string YouNotCreatedThisAd {
            get {
                return ResourceManager.GetString("YouNotCreatedThisAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Not Have Enough Points.
        /// </summary>
        public static string YouNotHaveEnoughPoints {
            get {
                return ResourceManager.GetString("YouNotHaveEnoughPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Account Has Been Deleted.
        /// </summary>
        public static string YourAccountHasBeenDeleted {
            get {
                return ResourceManager.GetString("YourAccountHasBeenDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youre Account Is Blocked.
        /// </summary>
        public static string YoureAccountIsBlocked {
            get {
                return ResourceManager.GetString("YoureAccountIsBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re Already Followed.
        /// </summary>
        public static string YoureAlreadyFollowed {
            get {
                return ResourceManager.GetString("YoureAlreadyFollowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youre Already Have Chat.
        /// </summary>
        public static string YoureAlreadyHaveChat {
            get {
                return ResourceManager.GetString("YoureAlreadyHaveChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Password Is.
        /// </summary>
        public static string YourPasswordIs {
            get {
                return ResourceManager.GetString("YourPasswordIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Points.
        /// </summary>
        public static string YourPoints {
            get {
                return ResourceManager.GetString("YourPoints", resourceCulture);
            }
        }
    }
}
